services:
  - type: web
    name: gpsquiz-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_INSTALL_URL
        sync: false
